namecoin/namecoin-core

- contrib/gitian-descriptors/gitian-linux.yml
This should fix Linux Gitian builds.
> Renamed bitcoin to namecoin in the Gitian Linux descriptor.

- src/qt/splashscreen.cpp
> black text for splashscreen

- src/qt/guiutil.cpp
> Windows Autostart to Namecoin

- README.md
- doc/README.md
This is roughly the same as https://github.com/namecoin/namecoin-core/pull/10 , but with a couple extra fixes, and rebased to current Namecoin Core code.
> Edit readme for Namecoin

- contrib/gitian-descriptors/gitian-linux.yml
Fixes https://github.com/namecoin/namecoin-core/issues/36
> Fix Linux Gitian default remote URL

- qa/rpc-tests/name_registration.py
- qa/rpc-tests/test_framework/names.py
- src/main.cpp
- src/miner.cpp
- src/wallet/rpcnames.cpp
This is my proposed fix for https://github.com/namecoin/namecoin-core/issues/50.  See there for more information about the underlying issue.
> Fix rejection of invalid name_firstupdate's from mempool.

- src/Makefile.bench.include
- src/Makefile.qttest.include
- src/Makefile.test.include
- src/bitcoin-cli-res.rc
- src/clientversion.h
- src/qt/test/test_main.cpp
- src/test/test_bitcoin.cpp
fix https://github.com/namecoin/namecoin-core/issues/55
> Rename Bitcoin to Namecoin

- share/setup.nsi.in
This is needed for the Windows Gitian builds to succeed, and also improves UX for Windows users.
This is only for 0.12 branch, do not merge to master since we will try to get abstractions merged upstream.
> Replaced Bitcoin with Namecoin in NSIS script.  

- doc/gitian-building.md
> Docs: rebrand gitian-building.md (0.12 branch)

- src/init.cpp
Self-explanatory commit title.
> Amend URL strings for "About Namecoin Core" pop-up.

- doc/release-process.md
> Docs: Fix paths in release process.  (master branch)

- doc/release-process.md
> Docs: Fix paths in release process.  (0.13 branch)

- .travis.yml
This will hopefully fix one of the Travis CI failures on the dev branch.
This PR is blocked by https://github.com/namecoin/namecoin-core/pull/155 and https://github.com/namecoin/namecoin-core/pull/156 ; don't merge for now.
> [WIP] Tests: Rename Bitcoin to Namecoin in Travis-CI.

- Makefile.am
- contrib/macdeploy/custom_dsstore.py
- contrib/macdeploy/detached-sig-create.sh
- contrib/macdeploy/fancy.plist
- contrib/macdeploy/macdeployqtplus
- share/qt/Info.plist.in
Refs #167 
I can't test this PR since I no longer have access to the OU lab with the macOS machine.
> Build: macOS: Rebrand filenames.

- doc/build-unix.md
> Docs: Rebrand Unix build notes for Namecoin

- src/chainparams.cpp
The other one is broken at time of writing.
(Disclaimer: the author of this commit is the operator of ncts.roanapur.info)
> Add new testnet DNS seed

- src/chainparams.h
https://github.com/xaya/xaya/issues/52
> fix illegal instruction failure in Qt on Darwin

- src/coins.cpp
- src/coins.h
- src/names/main.cpp
- src/rpc/names.cpp
- src/txdb.cpp
- src/txdb.h
Hello! Adding this boost header fixes the WSL windows build. Probably not the right place for it but a good conversation starter?
> Boost thread header for txdb.

- src/qt/forms/managenamespage.ui
- src/qt/managenamespage.cpp
This PR adds the "Renew Names" button to the GUI.
> Add "Renew Names" button

- src/qt/transactionrecord.cpp
- src/qt/transactionrecord.h
- src/qt/transactiontablemodel.cpp
- src/qt/transactionview.cpp
This PR adds the appropriate decoration to name operations in the Overview and Transactions tabs.
> Name decoration in Qt GUI

- src/interfaces/wallet.h
- src/qt/transactionrecord.cpp
- src/wallet/interfaces.cpp
- src/wallet/receive.cpp
- src/wallet/transaction.h
- src/wallet/wallet.cpp
- src/wallet/wallet.h
Lays the groundwork for https://github.com/namecoin/namecoin-core/issues/434
> Add decoration for name renewals

- src/qt/transactionrecord.cpp
- src/qt/transactionrecord.h
- src/qt/transactiontablemodel.cpp
Removes redundant UI info, improving UX.
> Move name operation into "Type" column

- src/qt/transactionrecord.cpp
- src/qt/transactionrecord.h
- src/qt/transactiontablemodel.cpp
> Add decoration for incoming name transfers

- src/qt/transactionrecord.cpp
- src/qt/transactionrecord.h
- src/qt/transactiontablemodel.cpp
> Add decoration for outgoing name transfers

- src/qt/bitcoingui.cpp
Fixes https://github.com/namecoin/namecoin-core/issues/398
> Clarify "Receive" tooltip

- src/qt/forms/managenamespage.ui
- src/qt/managenamespage.cpp
- src/qt/managenamespage.h
- src/qt/walletview.cpp
Fixes https://github.com/namecoin/namecoin-core/issues/316
> Add Export button to Manage Names tab

- contrib/guix/INSTALL.md
- contrib/guix/README.md
- contrib/guix/guix-build
- contrib/guix/guix-codesign
- contrib/guix/libexec/codesign.sh
- contrib/guix/libexec/prelude.bash
- doc/guix.md
- doc/release-process.md
This PR fixes the Guix scripts and documentation for Namecoin.
> Rebrand Guix

- doc/build-unix.md
Replace Bitcoin with Namecoin.
> Rebrand build-unix docs

- src/qt/nametablemodel.cpp
- src/qt/nametablemodel.h
Fixes https://github.com/namecoin/namecoin-core/issues/457
> Fix double lock when creating a new wallet

- src/qt/forms/managenamespage.ui
Uses "Edit" icon from Bitcoin Core.
> Add icon for Configure Name button

- src/qt/forms/managenamespage.ui
- src/qt/managenamespage.cpp
- src/qt/managenamespage.h
Fixes https://github.com/namecoin/namecoin-core/issues/272
> Add name count label

- contrib/guix/INSTALL.md
- contrib/guix/README.md
- contrib/guix/guix-build
- contrib/guix/guix-codesign
- contrib/guix/libexec/codesign.sh
- contrib/guix/libexec/prelude.bash
- doc/guix.md
- doc/release-process.md
> Rebrand Guix (22.x backport)

- src/qt/nametablemodel.cpp
- src/qt/nametablemodel.h
> Fix double lock when creating a new wallet (22.x backport)

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/good_first_issue.md
- .github/ISSUE_TEMPLATE/gui_issue.md
- .github/PULL_REQUEST_TEMPLATE.md
Some users have informed me that the issue templates on this repo are confusing; this PR rebrands them to cover Namecoin.
> Rebrand issue templates

- src/qt/buynamespage.cpp
- src/qt/buynamespage.h
- src/qt/forms/buynamespage.ui
- src/qt/nametablemodel.cpp
Similar functionality already exists in Electrum-NMC.
> Add availability check to Buy Names tab

- src/chainparams.cpp
This DNS seed is operated by `/u/mjgill89` on Reddit.
> Net: Add mainnet DNS seed from mjgill89

- src/names/applications.cpp
- src/names/applications.h
- src/qt/transactionrecord.cpp
- src/test/name_applications_tests.cpp
domob: Added dummy description to make the merging script work.
> Show `.bit` form for `d/` names in `TransactionRecord`

- src/qt/configurenamedialog.cpp
- src/qt/configurenamedialog.h
- src/qt/forms/configurenamedialog.ui
Fixes https://github.com/namecoin/namecoin-core/issues/505
This PR was funded by Cyphrs.
> Show value size in Configure Name dialog

- src/kernel/chainparams.cpp
yanmaani says this seed is permanently retired.
> Remove yanmaani's testnet DNS seed
