src/chainparams.cpp
Add dnsseeds running on webbtc.com. They are based on http://github.com/mhanne/bitcoin-ruby-dnsseed
=> Add webbtc.com dnsseeds for main- and testnet

src/qt/guiconstants.h
On Windows Namecore modifies/creates a Bitcoin registry entry (strDataDir) making Bitcoin disfunctional (if the Namecoin folder is not yet present).
=> guiconstants.h: Fix datadirpath / registry issue

src/bitcoin-cli-res.rc, src/bitcoin-tx-res.rc, src/bitcoind-res.rc, src/qt/res/bitcoin-qt-res.rc
At least on windows these are displayed in the task manager.
I left Namecore as product name as is the case in the Qt .rc file.
=> .rc files: Proper task names

.travis.yml
Fixes namecoin/meta#20.
Didn't actually setup Travis-CI and test this, but it should work according to the documentation.
=> Enable #namecoin-dev notification on travis-ci build failure

contrib/gitian-descriptors/gitian-linux.yml
This is a backport specifically for the 0.12 branch; do not merge to master.  Fixes https://github.com/namecoin/namecoin-core/issues/57
=> Fix version in name of Gitian Linux descriptor (0.12)

contrib/gitian-descriptors/gitian-win.yml
This fixes Gitian Windows builds for the 0.12 branch.  Do not merge to the master branch; master branch support is dependent on some pending upstream changes.
=> Fix Gitian Windows builds for 0.12 branch.

doc/release-process.md
See https://github.com/namecoin/namecoin-core/issues/73 .  If this PR is accepted, I will file another which backports this to the 0.12 branch.
=> Make release process docs refer to Namecoin

doc/release-process.md
This is a port of https://github.com/namecoin/namecoin-core/pull/82 to the 0.12 branch.
=> Make release process docs refer to Namecoin (0.12 branch)

doc/gitian-building.md
The gitian-building.md instructions contain references and instructions for Bitcoin.  While these are easy to mentally convert to Namecoin instructions for people who are familiar with Gitian usage, it's better to explicitly change the relevant instructions to apply to Namecoin. I've already seen one person report issues because the documentation was unclear, and even for people who can mentally convert, decreasing cognitive load is a good thing.
This is a logical extension of #82 .
If this is merged, I will submit a similar PR for the 0.12 branch.
=> Docs: rebrand gitian-building.md

src/rpc/names.cpp
Added a reference to utilstrencodings.h, necessary to compile the RPC for names.
=> Add missing header file

contrib/gitian-descriptors/gitian-win.yml, share/setup.nsi.in
Replaces "bitcoin" or "Bitcoin" with "namecoin" or "Namecoin" respectively in the NSIS script and Windows Gitian descriptor.  This allows Windows builds to succeed with Gitian.
Fixes https://github.com/namecoin/namecoin-core/issues/37 .  Fixes https://github.com/namecoin/namecoin-core/issues/68 .
=> Build system: fix Gitian builds for Windows

doc/release-process.md
Fixes and cleanup related to the recent conflicting merge.  Fixes https://github.com/namecoin/namecoin-core/issues/91 .
=> Docs: fix regressions in Release Process from 88b41237b2fc5b9146715525287a7cfe8a0fa5bd

src/policy/policy.h
Disable the standard-ness check for low-S signatures that was introduced by upstream Bitcoin.  This is not consensus-relevant.
The check conflicts with transactions created by the legacy client, so this change makes miners using the new client accept transactions produced by it.
=> Temporarily disable low-s check.

doc/release-process.md
Namecoin Core's repo name is `namecoin-core`, not `namecoin`, so the `gbuild` and `gsign` commands should use `namecoin-core` in the path to the `.yml` files.
Note that this also needs to be backported to master and 0.13.
=> Docs: Fix paths in release process.

qa/rpc-tests/name_rawtx.py, src/names/main.h, src/validation.cpp
This fixes #116.  The crash described there happens when adding an invalid transaction to the mempool, since the constructor of `CTxMempoolEntry` assumes that we have a valid structure for name tx (at most one name input/output).  This is checked only later at the moment, failing an assertion.
This patch introduces an earlier check for the validity of a Namecoin transaction when adding to mempool, so that this assumption is actually valid later on.  The check still happens as part of `CheckInputs`, which is redundant for the mempool addition (not block verification) but that is no problem.
=> Introduce an earlier check for invalid Namecoin tx

doc/build-osx.md
Re-implementation of #97 for the current dev branch.
I've tested this on an OS X machine kindly provided by OU.
=> Docs: Rename Bitcoin to Namecoin in OS X build docs.

Makefile.am
This PR will need to be reverted after AAA is deployed.
This fixes one of the Travis CI failures on the dev branch.
Refs #142
=> Tests: Fix Makefile.am's txcreatesign and blanktx dependencies.

src/chainparams.cpp
BIP65 finally activated with `nVersion=4` on Namecoin mainnet.  Set the activation height to block 335k (at which it was already fully active).
Please check carefully and ACK if this looks good.  Then I'll merge this on `dev` and `dev-0.14`, and rename the branches accordingly.  (`dev-0.14` to `0.14`, `master` to `legacy-pre-0.14` and `dev` to `master`, unless someone has better suggestions.)
=> Set activation height of BIP65.

doc/REST-interface.md
The new ports are 8336 and 18336, instead of 8332 and 18332 used before.
=> Docs: Update default ports in REST API documentation

src/protocol.h
Basically, P2P propagated addresses and addresses from DNS seeds were not being used to connect out to any other nodes. This is the smallest change that fixes that, and allows my node to get a full set of outbound peers now.
I believe that this fixes these issues:
https://github.com/namecoin/namecoin-core/issues/145
https://github.com/namecoin/namecoin-core/issues/174
https://github.com/namecoin/namecoin-core/issues/188
=> GetDesirableServiceFlags: Do not desire NODE_WITNESS

contrib/gitian-descriptors/gitian-win.yml
Should fix a Gitian Windows build error that was occurring.
=> Build: Rebrand Gitian Windows descriptor to Namecoin

doc/release-process.md
Various changes from upstream Bitcoin Core weren't properly merged into Namecoin Core; this PR fixes that.
=> Docs: Fix merge conflicts in release process docs.

src/chainparams.cpp
There is only one other functional DNS seed (quisquis), and it doesn't work under all DNS resolvers (didn't work under Comcast's default one, worked with OpenNIC and google). I've set up and added a new one.
=> Net: added markasoftware.com dns seed

src/qt/forms/modaloverlay.ui
The modal overlay referenced "bitcoin" and currency transactions; this PR changes "bitcoin" to "namecoin" and clarifies that the unsynced status impacts name updates and name lookups, not just currency transactions.
=> Qt: Rebrand modal overlay

doc/release-process.md
OS X Gitian builds should work now, so there's no reason to exclude them from the Release Process docs.
=> Docs: Re-enable OS X builds in Release Process docs.

contrib/devtools/check-rpc-mappings.py
The script `contrib/devtools/check-rpc-mappings.py` verifies consistency between RPC dispatch tables and the argument conversions listed in `src/rpc/client.cpp`.  For this, it needs a list of sources that contain dispatch tables.  `src/rpc/names.cpp` was missing from this list, leading to errors as in #203.
This commit adds the missing source file, which makes the script run successfully.  Note that `src/wallet/rpcnames.cpp`, which also contains Namecoin RPCs, need not be listed; the dispatch table for those RPCs is included in `src/wallet/rpcwallet.cpp.`
=> Add src/rpc/names.cpp to check-rpc-mappings.py source list.

src/Makefile.am, src/init.cpp, src/rpc/auxpow_miner.cpp, src/rpc/auxpow_miner.h, src/rpc/mining.cpp, src/rpc/mining.h, src/test/auxpow_tests.cpp, src/wallet/rpcwallet.cpp
This implements https://github.com/namecoin/namecoin-core/issues/224:  It creates a new `AuxpowMiner` class to hold the previously-global state and the logic of the merge-mining RPCs.  This separates the code better from the upstream `rpc/mining.cpp` code, and gets rid of all the global and in-function static variables.  Instead, there is now a clear construction and desctruction of the `AuxpowMiner` used during the startup and shutdown sequences.
By separating the code off, we can also add unit tests for the block (re)generation logic.
=> Create AuxpowMiner helper class

src/rpc/names.cpp, src/wallet/rpcnames.cpp, test/functional/name_sendcoins.py, test/functional/run_name_tests.sh, test/functional/test_runner.py
This (building on top of #220 - I will rebase after #220 is merged before merging this one) adds the new `sendCoins` option to name operations (`name_new`, `name_firstupdate` and `name_update`).  This allows to (optionally) send coins in the same transaction as a name update, similar to `sendmany`.
This is a feature we need for Chimaera - but since it applies to Namecoin as well and might be useful there also, I think we should implement it here.
If there are no NACKs or other feedback in the next few days, I will merge this early next week.
=> Add "sendCoins" option for name operations

src/core_io.h, src/core_write.cpp, src/wallet/rpcwallet.cpp, test/functional/name_listunspent.py, test/functional/run_name_tests.sh, test/functional/test_runner.py
Previously, `listunspent` did not explicitly handle name outputs - and as a consequence, they were just shown mixed in with (and undistinguishable from) the currency outputs.  This adds explicit handling:
* Any *expired* name outputs are always excluded, as they are unspendable.
* Other name outputs are included in the results only if the new `includeNames` RPC option, which is off by default, is set.
* If name outputs are included in the result, then they are marked by a `nameOp` field equivalent to that of `decoderawtransaction`.
This implements https://github.com/namecoin/namecoin-core/issues/192.
=> Handle name outputs in listunspent

src/miner.cpp, test/functional/name_immature_new.py, test/functional/run_name_tests.sh, test/functional/test_runner.py
When creating blocks from the mempool, miners need to make sure that they do not include `name_firstupdate` transactions with still immature `name_new` inputs; those are allowed in the mempool but not in the blockchain (but they will be fine once the name_new is mature enough).
There is already logic to ensure that, but it had a bug that did not prevent `name_firstupdate`'s to be included in blocks if the corresponding `name_new` was actually *unconfirmed*.
This caused https://github.com/namecoin/namecoin-core/issues/50 and presumably also https://github.com/namecoin/namecoin-core/issues/227.
With this commit, we fix the underlying bug and add regression tests that exercise and cover this scenario (as well as general handling of immature / unconfirmed inputs to name operations).
=> Correctly handle unconfirmed name_new in mining

src/auxpow.cpp, src/auxpow.h, src/rpc/blockchain.cpp, src/rpc/mining.cpp, src/test/auxpow_tests.cpp, src/test/validation_block_tests.cpp, src/validation.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
This is a collection of code cleanups for the `CAuxPow`-related code.  Some internals are made private to enforce better encapsulation, and the dependency-issue of `CMerkleTx` described in #231 is fixed by introducing a `CBaseMerkleTx` class.
=> Clean up auxpow code

contrib/auxpow/getwork-wrapper.py, contrib/auxpow/getwork-wrapper.sh, test/functional/test_framework/auxpow.py
This is a small Python script (added in `contrib/auxpow`) which wraps around `getauxblock` of the daemon and provides a `getwork`-like RPC interface for miners.  This can be used to "merge mine" Namecoin blocks with an existing SHA256D mining software.
Note that this is not meant to be useful in production mining; but it can be used for testing and debugging.  Also, it provides a simple example for how merge-mining can be implemented on the miner's side.
=> Add simple script for stand-alone "merge" mining

src/rpc/names.cpp, src/rpc/server.h, src/wallet/rpcnames.cpp, test/functional/interface_rest.py, test/functional/name_ismine.py, test/functional/name_list.py, test/functional/name_rawtx.py, test/functional/run_name_tests.sh, test/functional/test_runner.py
Based on the proposal in #219, this change removes the `transferred` field in the `name_list` output.  Instead, it adds the `ismine` field from `name_pending` consistenly to the output of all name RPCs (`name_show`, `name_history`, `name_scan`, `name_filter` and `name_list`, in addition to `name_pending` where it already is).
When the daemon is compiled with wallet support and the user has a wallet, then the `address` field that is already returned from all of them is checked against the wallet to populate `ismine`.  Everything should still work (same as `name_pending` now) even without a wallet, though, so this is strictly optional new functionality.
This change also adds a dedicated regtest for `ismine` in all RPCs.
=> Consistently add "ismine" field to all name RPCs

doc/release-notes-namecoin.md, src/rpc/names.cpp, src/rpc/names.h, src/wallet/rpcnames.cpp, test/functional/name_registration.py
As proposed in #54, this leverages the new `options` argument to `name_new` to prevent accidental `name_new` transactions where the name exists already.  To do this, we add a new `allowExisting` field in the `options` and only allow sending a `name_new` for an existing name if that option is explicitly set by the user.
Relative to the current behaviour, this changes the "default" but still keeps the option for power users to override the check and get back the old behaviour.  Also, of course, there are no changes on the consensus level.
=> Add "allowExisting" option for name_new

src/consensus/tx_verify.cpp, src/names/main.cpp, test/functional/mining_basic.py
When `CheckNameTransaction` fails because the prev tx input is not found, return the same `bad-txns-inputs-missingorspent` error code that upstream Bitcoin returns, rather than a general "name tx verification failed" one.  This allows us to stick closer to upstream code in the test also.
For all other cases, if no specific error code is returned from `CheckNameTransaction`, return at least a new `tx-invalid-nameop` code and `REJECT_INVALID`.
=> More explicit error code for missing tx input

doc/release-notes-namecoin.md, src/Makefile.am, src/bitcoin-tx.cpp, src/core_write.cpp, src/init.cpp, src/names/common.h, src/names/encoding.cpp, src/names/encoding.h, src/names/main.cpp, src/rest.cpp, src/rpc/names.cpp, src/rpc/names.h, src/rpc/protocol.h, src/test/name_tests.cpp, src/txdb.cpp, src/univalue/include/univalue.h, src/univalue/lib/univalue.cpp, src/wallet/rpcnames.cpp, src/wallet/wallet.cpp, test/functional/interface_rest.py, test/functional/name_encodings.py, test/functional/name_scanning.py, test/functional/name_wallet.py, test/functional/run_name_tests.sh, test/functional/test_runner.py, test/util/data/bitcoin-util-test.json, test/util/data/name_update_encoding.json
This implements the main part of the proposal in #246:  New `-nameencoding` and `-valueencoding` options are added, with the possible values of `ascii`, `utf8` and `hex`.  They specify in which encoding name and value data is expected in RPC arguments and returned in JSON fields.  This fixes a long-standing issue Namecoin had with binary data that was invalid UTF-8 (as well as adding proper support for real binary data in the RPC interface).  As a consequence, this likely resolves (or is at least a big part of the solution of) #152 and #170.
Still missing for a full solution of #246 is the possibility to specify per-RPC encodings in an `options` RPC argument.  For now, the encodings can only be set for the full process at startup time through the config options.
=> Main support for name/value encodings

doc/release-notes-namecoin.md, src/validation.cpp, test/functional/rpc_signmessage.py
`signmessage` and `verifymessage` use a "magic string" prefix.  Previously, Namecoin was using the same as upstream Bitcoin.  This has the confusing effect that signatures can be interchanged between Bitcoin and Namecoin.  (But of course, someone still has to own the private key to create a valid signature for any of them in the first place.)
This commit changes the magic string to be specific to Namecoin, which makes sure that messages signed in Namecoin can only be validated in Namecoin, and messages signed in Bitcoin only with Bitcoin (as most people likely expect).
Note that this means that old signatures won't validate anymore with `verifymessage`.  But it is probably unlikely that this was used a lot at all.  Furthermore, the signature can of course still be verified in a custom way …
=> Update the signmessage "magic string"

src/rpc/blockchain.cpp, test/functional/name_utxo.py, test/functional/rpc_blockchain.py, test/functional/run_name_tests.sh, test/functional/test_runner.py
Add explicit logic to `gettxoutsetinfo` that separates the amounts locked in names from the amounts available in coins.  Also adds a new regtest specifically for the interaction of names with the UTXO set.
This fixes https://github.com/namecoin/namecoin-core/issues/251.
=> Handle names for gettxoutsetinfo

src/Makefile.test.include, src/policy/policy.cpp, src/qt/coincontroldialog.cpp, src/script/interpreter.cpp, src/script/script.cpp, src/script/script.h, src/script/standard.cpp, src/test/script_segwit_tests.cpp, src/wallet/wallet.cpp, test/functional/name_segwit.py, test/functional/run_name_tests.sh, test/functional/test_runner.py
This fixes an issue with names and native segwit scripts (bech32 addresses).  `CScript::IsWitnessProgram` did not strip name prefixes, which meant that names at bech32 addresses were anyone-can-spend even after segwit activation - but the transaction had to be included in a block, since the transaction would be rejected by a non-mandatory rule from the mempool.  P2SH-Segwit is already working as expected.
With this fix, names should work well together with segwit in all variants.  This also includes tests to verify that, including (but not limited to) the situations described in #258.
Note that this is in theory a consensus change, but it is safe to commit because segwit is not yet active for Namecoin.
This includes a cherry-pick from https://github.com/bitcoin/bitcoin/pull/14752, to …
=> Fix for names and native segwit + tests

doc/release-notes-namecoin.md, src/rpc/names.cpp, test/functional/name_ismine.py
When no wallet is associated to an RPC call like `name_show`, do not include `ismine` in the result at all.  Previously, `ismine=false` was returned in those cases.  But this is misleading, as it implies that the name is certainly *not* in the wallet.
Instead, we now do not include `ismine` as wallet-specific field at all. This means that especially multi-wallet situations without a specified wallet now behave in the same way as if the wallet were not compiled in at all.  This makes the behaviour consistent.
Note that standard situations where the user has exactly one wallet are not affected at all by this change.  Only multi-wallet users are.
=> Remove "ismine" for RPC calls without wallet.

src/rpc/blockchain.cpp
The `getblock` help text was missing a description of the `auxpow` field in the returned JSON object.  This adds the missing help text.
Note that the field itself was already present and is not changed.  This is purely about the documentation in the online help.
Fixes https://github.com/namecoin/namecoin-core/issues/289.
=> Add auxpow to getblock help text

contrib/namecoin/convertBechAddress.sh
`convertBechAddress.sh` wasn't exporting the `PYTHONPATH` variable, so Python couldn't see the variable, which caused `ImportError: No module named 'segwit_addr'` if the bech32 library wasn't already in the system Python path.
=> Fix PYTHONPATH in convertBechAddress.sh

test/functional/auxpow_invalidpow.py, test/functional/test_framework/messages.py, test/functional/test_runner.py
The new regtest verifies that it is "fine" to submit a valid block with invalid auxpow, and that this does not permanently mark the block as invalid.  In other words, the node will later still accept the block if a valid auxpow is supplied.
If this were not the case, then this could be used to fork the network.  The behaviour of the main validation code is already good, but by adding an explicit test we can ensure that we do not regress on this.
=> Add test for valid block with invalid auxpow

src/auxpow.cpp, src/auxpow.h, src/rpc/blockchain.cpp, src/test/auxpow_tests.cpp, src/wallet/wallet.h, test/functional/auxpow_mining.py, test/functional/auxpow_zerohash.py, test/functional/test_runner.py
This change refactors the auxpow code so that the `hashBlock` field of a serialised `CAuxPow` is always set to zero.  Since that field is never actually used or checked in code (also not in the existing network without this change), that is a safe change to make.  It increases compressibility of the data, which can help SPV clients (see #288 for discussion about that).
In addition, this also changes the code to ignore the `nIndex` field when deserialising a `CAuxPow`.  This value is not necessary either, as it has to be always zero (for a coinbase tx as in an auxpow).  This change affects consensus:  Nodes with this patch applied will accept auxpows with a non-zero `nIndex`, while nodes without will reject those auxpows.  But since the auxpow is only there to provide PoW for a block and …
=> Set auxpow "hashBlock" to zero

src/rpc/auxpow_miner.cpp, src/rpc/auxpow_miner.h, test/functional/auxpow_mining.py
AuxpowMiner::createAuxBlock() only caches a single block for a specific height. If we call createauxblock RPC multiple times with different coinbase payout addresses in that case, they will actually all use the first address. This commit uses a map with the coinbase transaction script hash as the cache so that we can get the correct results.
=>  Allow createauxblock RPC with different coinbase addresses

src/validation.cpp, test/functional/name_multiupdate.py, test/functional/run_name_tests.sh, test/functional/test_framework/names.py, test/functional/test_runner.py
Namecoin's memory pool implementation does not allow multiple updates to a single name (in a chain), but the consensus logic is fine with that.  In other words, it is possible to update a name multiple times in a single block as long as those updates are in that one block.
This adds a regression test for this situation as well as the mempool handling, to make sure that the current and expected state is preserved and no accidental regression is introduced with this edge case.
Also includes a tiny change to the logic of the mempool acceptance itself, so that a proper error code is returned if accepting a transaction fails due to name rules.
=> Test multiple updates of a name in one block

src/chainparams.cpp
This schedules a softfork activating BIP16 (P2SH), Segwit and CSV at a future blockheight on mainnet and testnet.
On mainnet, the activation will happen at block **475,000**, which is expected to be mined in about half a year.  On testnet, the activation happens at block 232,000, or in one to two weeks (but depending strongly on the mining activity on testnet).
See #239 for a discussion, including the commitment to update timely by many of the most important
mining pools.
=> Schedule segwit activation softfork.

doc/release-process.md
Namecoin Git tags use the `nc` prefix, not Bitcon's `v` prefix.
=> Docs: Rebrand Git tags in release process to Namecoin

doc/gitian-building.md
The use of Bitcoin Core's docs repo was confusing some users; this PR links to a new Namecoin fork of that repo instead.
=> Docs: Link to new namecoin-core-docs repo

doc/release-notes-namecoin.md, src/names/main.cpp, src/names/mempool.cpp, src/names/mempool.h, src/rpc/names.cpp, src/test/name_mempool_tests.cpp, src/txmempool.h, src/wallet/rpcnames.cpp, test/functional/name_multiupdate.py, test/functional/name_registration.py, test/functional/test_framework/names.py
This removes the mempool-restriction of allowing only one update per name and block.  That restriction was introduced originally to simplify the mempool implementation, but is actually easy to lift.
With this change, we allow a chain of updates of one name to be in the mempool at once; this can be useful e.g. to quickly fix an erraneous previous update without the need to wait for confirmations in between.  For `name_new` and `name_firstupdate`, no changes are made.  Only updates are allowed to be chained on a pending operation, although updates can be chained to a `name_firstupdate`.
Note that the consensus layer of Namecoin already allows such chains, and the restriction lifted is purely a policy one (in other words, this is not a fork of any sort).  For now, we only remove the …
=> Allow multiple updates of a name per block

test/functional/name_expiration.py, test/functional/name_list.py, test/functional/name_multisig.py, test/functional/name_pending.py, test/functional/name_rawtx.py, test/functional/name_registration.py, test/functional/name_reorg.py, test/functional/name_sendcoins.py, test/functional/name_wallet.py, test/functional/test_framework/names.py
This set of commits streamlines the Namecoin regtests, mostly the old ones that have been around for a couple of years without significant refactoring.  In particular, we now use the `invalidateblock` and `reconsiderblock` RPCs to test reorgs, rather than using separate nodes and splitting / joining the network (which used to be the only way to do those tests back in the day).
Also, in general we reduce the number of test nodes as much as possible, and avoid syncing between them where it is not necessary.  These syncs are the main cause of slowness in the Namecoin regtests.
This speeds up the tests massively, and at the same time makes them easier to read/understand, because the reader no longer needs to mentally keep track of so many different nodes and their states/roles.
=> Streamline and speed up regtests

doc/release-notes-namecoin.md, src/Makefile.am, src/index/namehash.cpp, src/index/namehash.h, src/init.cpp, src/rpc/names.cpp, src/rpc/names.h, test/functional/name_byhash.py, test/functional/test_runner.py
This set of changes implements https://github.com/namecoin/namecoin-core/issues/329:  A new option `-namehashindex` allows running Namecoin Core in a way that keeps an additional database of name hashes to preimages for all registered names.  When this is enabled, the new `byHash` option can be passed to `name_show` and `name_history` to request name lookup by hash rather than direct.
This is useful because it allows using an external node to check if a given name is registered or not, without revealing the name itself if it does not exist yet.  This may be useful for Electrum (and perhaps other light clients) in the future.
=> Implement name lookups by hash

README.md
That URL is wrong, there are in fact binaries, and there's been binaries since at least 2013.
=> Update README.md to reflect new binary situation

doc/release-notes-namecoin.md, src/init.cpp, src/rpc/names.cpp, src/rpc/names.h, test/functional/name_allowexpired.py, test/functional/name_expiration.py, test/functional/name_listunspent.py, test/functional/name_registration.py, test/functional/name_utxo.py, test/functional/name_wallet.py, test/functional/test_runner.py
This set of changes makes `name_show` throw an error for expired names. This behavior can be overridden by setting the `allowExpired` RPC option to true, or by using the `-allowexpired` command-line parameter.
This behavior is discussed in issue #194.
=> rpc: Make name_show RPC command error for expired names

doc/release-notes-namecoin.md, src/rpc/names.cpp, test/functional/name_ant_workflow.py, test/functional/name_psbt.py, test/functional/test_runner.py
This adds a new RPC method, `namepsbt`.  It works in the same way as `namerawtransaction` to add a name operation to an existing output, but operates on PSBTs rather than hex-format raw transactions.  This fixes #361.
With this, it is possible to go through the entire name-trading workflow with just PSBTs and without any hex-format raw transactions.  However, it is not yet possible to let the wallet fund the transaction, as that requires funding without the out-of-wallet name input first and only later adding it to the PSBT.  Once https://github.com/bitcoin/bitcoin/issues/19608 is implemented, this will be possible as well.
=> Add namepsbt RPC method

src/wallet/rpcnames.cpp, test/functional/name_novalue.py, test/functional/test_framework/names.py, test/functional/test_runner.py
This patch amends `name_firstupdate` and `name_update` to make the `value` parameter optional. As proposed in #372, a missing value in `name_firstupdate` equals the empty string, and a missing value in `name_update` equals the last value of the name.
It also amends the test suite to support writing tests that do not furnish name values. That change is intended to make it easier to write future tests; it isn't relied upon by the test of the implemented feature, which uses direct RPC calls.
Fixes #372.
=> Make name value optional in name_firstupdate and name_update

ci/test/06_script_a.sh
Fixes a Cirrus failure in the `Cirrus CI / 32-bit + dash [gui] [CentOS 8]` build.
=> Rebrand Cirrus build directory

src/auxpow.h, src/rpc/auxpow_miner.h, src/test/auxpow_tests.cpp
This fixes some small oversights in the `auxpow` code that fail compilation with `clang` due to static analysis or other warnings, as pointed out by Cirrus CI.
Fixes #388.
=> Fix some auxpow CI errors

src/qt/forms/managenamespage.ui, src/qt/managenamespage.cpp, src/qt/managenamespage.h, src/qt/nametablemodel.cpp, src/qt/nametablemodel.h
Port of the name renew Qt GUI to master branch.
Fixes https://github.com/namecoin/namecoin-core/issues/377 .
=> name renew Qt GUI

contrib/gitian-build.py
This PR fixes a bug where `gitian-build.py --build` would result in the error `../namecoin/depends: No such file or directory`.
This will also need to be backported to the `0.21` branch (I expect it to cherry-pick cleanly).
=> Fix Gitian path for depends

contrib/gitian-descriptors/assign_DISTNAME
This PR fixes a bug where `gitian-build.py --build` would result in the error `mv: cannot stat 'build/out/namecoin-*.tar.gz': No such file or directory`.
This will also need to be backported to the `0.21` branch (I expect it to cherry-pick cleanly).
=> Rebrand Gitian distname

contrib/macdeploy/README.md
This will also need to be backported to the `0.21` branch, but it will probably not cherry-pick cleanly, so I'll send a separate PR for the backport once this is merged.
=> Rebrand macOS deploy readme

contrib/macdeploy/README.md
Backport of https://github.com/namecoin/namecoin-core/pull/402 to `0.21`.
=> Rebrand macOS deploy readme (0.21 backport)

src/qt/nametablemodel.cpp
The name tab's model was resetting itself every time `name_list` was called.  Resetting a model is somewhat drastic and disruptive, e.g. it also resets which rows the user has selected.  This PR instead edits the existing contents of the name tab model, so the user-selected rows get preserved.
=> Edit contents of model instead of resetting

src/qt/nametablemodel.cpp, src/qt/nametablemodel.h
This PR adds the `name_pending` GUI, and also adds the GUI for the `ismine` and `expired` fields in `name_list`.
=> name_pending Qt GUI

src/Makefile.am, src/Makefile.test.include, src/wallet/rpcnames.cpp, src/wallet/rpcnames.h, src/wallet/test/rpcnames_tests.cpp, test/functional/name_deterministic_salt.py, test/functional/test_runner.py
This patch amends `name_new` and `name_firstupdate` to, respectively, register new names with deterministically generated salts, and to try using such salt as `rand` value if no salt is provided.
If it is not possible to generate such salt, e.g. because the private key for the address to which the name is sent is not available, it will fall back to generating a random salt.
Closes #368.
=> Deterministic salts

src/Makefile.qt.include, src/qt/configurenamedialog.cpp, src/qt/configurenamedialog.h, src/qt/forms/configurenamedialog.ui, src/qt/forms/managenamespage.ui, src/qt/managenamespage.cpp, src/qt/managenamespage.h, src/qt/nametablemodel.cpp, src/qt/nametablemodel.h
This PR adds the `name_update` GUI.
=> name_update Qt GUI

src/wallet/rpcnames.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, src/wallet/walletdb.cpp, src/wallet/walletdb.h, test/functional/name_txnqueue.py, test/functional/test_runner.py
This patch adds a transaction queue to Namecoin, building off Jeremy Rand and Brandon Roberts' work (#266). Unfortunately, it is not yet ready for merge, since there is a bug in `listqueuedtransactions`.
I'm also unsure, should changelogs for this (and #422) go under 0.21 or 0.21.1?
Notes:
* New RPC `queuerawtransaction`
* New RPC `dequeuetransaction`
* New RPC `listqueuedtransactions`
* API has been simplified; caller is expected to use nSequence in queued transaction. Triggers have been removed.
* When a block is received, the transaction queue will be processed. This is done in `CWallet::blockConnected` to have access to the chain; it's a bit unseemly but I don't see a cleaner way to do it.
* **`listqueuedtransactions` hangs about 20% of the time trying to acquire a lock; the offending …
=> Transaction queue

src/qt/managenamespage.cpp
This PR disables the "Configure" and "Renew" options for names that are unspendable due to expiration or transfer.
=> Disable updating unspendable names

src/qt/askpassphrasedialog.cpp
Some users may not immediately understand that names are internally represented as coins.
=> Clarify "coins" in passphrase dialog

src/Makefile.qt.include, src/qt/bitcoingui.cpp, src/qt/bitcoingui.h, src/qt/buynamespage.cpp, src/qt/buynamespage.h, src/qt/forms/buynamespage.ui, src/qt/walletframe.cpp, src/qt/walletframe.h, src/qt/walletview.cpp, src/qt/walletview.h
This PR adds a GUI for `name_firstupdate`, based on Brandon's port of Mikhail's GUI.  AFAICT, once https://github.com/namecoin/namecoin-core/pull/436 is merged, patching this GUI to use `name_autoregister` instead should be roughly a one-liner.  Until then, it's still a UX improvement over the status quo, even though the user needs to run `name_new` themselves.
Refs https://github.com/namecoin/namecoin-core/pull/187
=> Add name_firstupdate GUI

src/qt/forms/managenamespage.ui
Slightly cleaner semantically than using 3 periods.
=> Use Unicode ellipsis

src/rpc/names.cpp
More detail is always good UX-wise.  Doesn't change the error code, so this isn't an API-breaking change.
=> Give more specific errors in name_show

contrib/shell/git-utils.bash
This enables properly stripping the `nc` prefix from Guix-built binaries.
=> Rebrand git-utils

src/chainparams.cpp
Adding two stable seed nodes for Namecoin MainNet, reachable on both IPv4 and IPv6.
=> Add 2 seed nodes (NMC MainNet)

src/chainparams.cpp
Fixes consistency with upstream Bitcoin, see https://github.com/namecoin/namecoin-core/commit/ca2c313aa291ae44adc1b7148ed49125bdc77bf4.
This should not be merged until https://github.com/namecoin/namecoin-core/pull/500 is merged and this PR is rebased accordingly.
=> Use absolute FQDN for DNS seed domains

src/Makefile.am, src/Makefile.test.include, src/names/applications.cpp, src/names/applications.h, src/qt/transactionrecord.cpp, src/qt/transactionrecord.h, src/qt/transactiontablemodel.cpp, src/test/name_applications_tests.cpp
Eliminates ambiguous "name" wording in favor of "domain"/"identity"/etc.  Also has the happy side effect of producing a scary "non-standard name" warning if someone tries to do a scam by selling a domain with whitespace at the end e.g. `d/wikileaks `.
=> Show namespace in Type column of Transactions tab

src/qt/buynamespage.cpp, src/qt/buynamespage.h
Both Namecoin Core 23.0 (https://github.com/namecoin/namecoin-core/issues/515) and 24.0, as shown below, fail to compile due to a missing #include.
This pull request resolves the issue in Namecoin Core 24.0 and subsequent releases. 
~~~
In file included from qt/buynamespage.cpp:1:
./qt/buynamespage.h:34:57: error: ‘optional’ in namespace ‘std’ does not name a template type
34 |     QString firstupdate(const QString &name, const std::optional<QString> &value, const std::optional<QString> &transferTo) const;
|                                                         ^~~~~~~~
./qt/buynamespage.h:7:1: note: ‘std::optional’ is defined in header ‘<optional>’; did you forget to ‘#include <optional>’?
6 | #include <QWidget>
+++ |+#include <optional>
7 | 
./qt/buynamespage.h:34:65: error: expected …
=> Missing #include in buynamespage.h

src/qt/forms/configurenamedialog.ui
The default order prioritized the Transfer widgets over the Data widget, which was suboptimal UX.
This PR was funded by Cyphrs.
=> Fix tab order in Configure Name dialog

src/qt/configurenamedialog.cpp
This brings those strings in line with Electrum-NMC.
This PR was funded by Cyphrs.
=> Use friendlier strings in Configure Name dialog

src/names/applications.cpp, src/names/applications.h, src/qt/configurenamedialog.cpp, src/qt/forms/configurenamedialog.ui, src/test/name_applications_tests.cpp
I added JSON verification functionality in names/applications.cpp alongside the associated unit tests and added them to the configure name dialog box. The dialog box should tell you if you inputted an invalid JSON value and warn you against configuring your domain with said invalid value, but should allow you to continue anyway if you were to insist.
=> Added JSON verification functionality for the Configure Name Dialog box

src/qt/transactionrecord.cpp
This particularly matters because the `name_new` RPC method sends to a change address by default, so if you issued a `name_new`, it would never show up in the Transactions tab.
=> Don't hide name ops sent to change addresses

src/names/applications.cpp, src/names/applications.h, src/qt/configurenamedialog.cpp, src/test/name_applications_tests.cpp
I added checking of JSON minimality in names/applications.cpp alongside the associated unit tests and added them to the configure name dialog box. The dialog box should tell you if you inputted an non-minimal JSON value and warn you against configuring your domain with said invalid value, but should allow you to continue anyway if you were to insist, as well as allow you to minimalise said JSON value before writing it onto the blockchain.
=> qt: added verification of minimal json in the configure name dialog box

src/names/common.h
Upstream Bitcoin Core refactored their endian conversion in 86b7f28d6c507155a9d3a15487ee883989b88943; make Namecoin follow suit.
Fixes a Guix build fail for Windows/x86_64 target.
=> Use internal endian conversion functions 

src/qt/buynamespage.cpp, src/qt/nametablemodel.cpp, src/qt/nametablemodel.h
Prevents corruption issues that were happening when default encoding wasn't ASCII.  Also a prereq to supporting binary data in the GUI.
=> Explicitly use hex encoding in GUI to RPC API

src/chainparamsbase.cpp
Refs https://github.com/namecoin/namecoin-core/issues/545
=> Avoid onion listen port collision

src/kernel/chainparams.cpp
The domain returns NXDOMAIN and is retired.
Refs https://github.com/namecoin/namecoin-core/issues/554
=> Remove Jonas Ostman's mainnet DNS seed
